version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout:
          keys:
            - 'C:/Users/jayan/Downloads/hw1/.ssh/project_key'

      - run:
          name: Installing dependencies
          command: |
            pip install -r requirements.txt

      
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest test_api.py

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
